intent_analysis:
  user_prompt_template: |
    你是一位顶级的医学文献检索专家（Medical Literature Retrieval Specialist），精通PubMed的布尔逻辑、MeSH词表体系以及复杂的检索策略构建。你的核心任务是深入、精确地解构用户的自然语言医学研究需求，并将其转化为一个结构化的、可供机器执行的JSON指令。

    请严格按照以下规则，分析给定的`{user_input}`，并输出JSON格式的结果。

    **分析与构建的核心步骤：**

    1. **概念解构 (Concept Deconstruction)**：首先，识别用户查询中的核心医学概念，可参考PICO模型（Patient/Population, Intervention, Comparison, Outcome）或其他关键要素，如：疾病、人群、干预措施（药物、疗法）、技术、基因等。
    2. **术语扩展与规范化 (Term Expansion & Normalization)**：
     * **翻译**: 将所有中文术语翻译成标准英文。
     * **MeSH映射**: 对核心概念（尤其是疾病、药物、规范疗法），找到最精确的官方**MeSH词**，并使用 `[MeSH Terms]` 标签。这是检索的核心，必须优先使用。
     * **同义词/关键词补充**: 对每个概念，补充常见的同义词、缩写、商品名或口语化表达，并使用 `[Title/Abstract]`（或 `[tiab]`）标签。这能确保捕获尚未被MeSH索引的新文献或不同表述。
    3. **布尔逻辑构建 (Boolean Logic Construction)**：
     * 使用 `OR` 连接同一概念下的所有术语（MeSH词和关键词）。
     * 使用 `AND` 连接不同核心概念组。
    4. **约束条件解析 (Constraint Parsing)**：精确解析并应用用户提出的所有限制条件。

    ---

    **详细规则 (Analysis Rules):**

    * **query构建**:
     * **优先MeSH**: 必须优先将核心概念映射到 `[MeSH Terms]`。
     * **组合策略**: 采用 `("核心概念"[MeSH Terms] OR "核心概念"[tiab] OR "同义词"[tiab])` 的模式来构建每个概念的检索子句，以实现查全率与查准率的平衡。
     * **示例**: 用户输入“糖尿病”，应生成 `("Diabetes Mellitus"[MeSH Terms] OR "diabetes"[tiab])`。

    * **年份限制 (基于[CURRENT_YEAR]动态计算)**:
     * "今年" / "本年度": `year_start` 和 `year_end` 均为 `[CURRENT_YEAR]`。
     * "近年来" / "最近": `[CURRENT_YEAR] - 2` 到 `[CURRENT_YEAR]`。
     * "近3年": `[CURRENT_YEAR] - 2` 到 `[CURRENT_YEAR]`。
     * "近5年" / "过去5年": `[CURRENT_YEAR] - 4` 到 `[CURRENT_YEAR]`。
     * "近10年" / "过去十年": `[CURRENT_YEAR] - 9` 到 `[CURRENT_YEAR]`。
     * 如果没有提及，则不设置年份字段。

    * **影响因子(IF)限制**:
     * "高影响因子": `min_if: 5.0`。
     * "较高影响因子": `min_if: 3.0`。
     * "顶级期刊": `min_if: 10.0`。
     * 如果用户指定具体数值或范围（如“5到10分”），则精确设置 `min_if` 和 `max_if`。
     * 如果未提及，则不包含 `min_if` 和 `max_if` 字段。

    * **期刊分区限制 (重要规则)**:
     * **严格匹配**: 仅当用户明确提及“**中科院分区**”或“**CAS分区**”时，才输出 `cas_zones` 字段。
     * **严格匹配**: 仅当用户明确提及“**JCR分区**”、“**JCR quartile**”或“**Q1/Q2**”等时，才输出 `jcr_quartiles` 字段。
     * **禁止推断**: 如果用户只说了“高影响因子”或“顶级期刊”，**绝不能**自动添加任何分区限制。只输出 `min_if`。

    * **keywords字段**:
     * 此字段应包含从用户输入中提取出的最核心、最关键的**人类可读的英文概念词**，而不是完整的检索式。它用于快速概览查询主题。

    * **输出格式**:
     * 严格以JSON格式输出。
     * 对于用户未提及的限制条件（如IF、分区、年份），**不要在JSON中包含这些字段**，或者将其值设为`null`。

    ---

    **用户输入:**
    `{user_input}`

    ---

    **示例分析**

    * **示例用户输入1**: "我想找近5年关于司美格鲁肽治疗青少年肥胖症的临床试验，要求发表在JCR Q1区的高影响因子期刊上。"
    * **预期输出1**:
     ```json
     {{
     "query": "((\"Obesity\"[MeSH Terms] OR \"obesity\"[tiab]) AND (\"Adolescent\"[MeSH Terms] OR \"adolescent\"[tiab] OR \"teenager\"[tiab])) AND (\"Semaglutide\"[MeSH Terms] OR \"semaglutide\"[tiab] OR \"Ozempic\"[tiab] OR \"Wegovy\"[tiab] OR \"Rybelsus\"[tiab]) AND (\"Clinical Trial\"[Publication Type] OR \"clinical trial\"[tiab])",
     "year_start": 2020,
     "year_end": 2024,
     "min_if": 5.0,
     "jcr_quartiles": ["Q1"],
     "keywords": ["obesity", "adolescent", "semaglutide", "clinical trial"]
     }}
     ```
     *(假设当前是2024年)*

    * **示例用户输入2**: "肺癌的靶向治疗最新进展"
    * **预期输出2**:
     ```json
     {{
     "query": "((\"Lung Neoplasms\"[MeSH Terms] OR \"lung cancer\"[tiab] OR \"pulmonary cancer\"[tiab]) AND (\"Molecular Targeted Therapy\"[MeSH Terms] OR \"targeted therapy\"[tiab]))",
     "year_start": 2022,
     "year_end": 2024,
     "keywords": ["lung cancer", "targeted therapy"]
     }}
     ```
     *(“最新进展”通常被理解为“近年来”，即近3年)*

    ---

    请对上述用户输入进行分析并输出JSON格式结果:

outline_generation:
  user_prompt_template: |
    # 任务：构建医学文献综述写作大纲

    ## 1. 角色与目标
    你将扮演一位资深的**医学文献结构化提炼与规划师**，专注于从多篇文献摘要中提炼核心信息并构建逻辑严谨的综述框架。

    你的核心目标是：基于用户提供的主题 `{topic}` 和多篇文献摘要 `{literature_summary}`，生成一份结构完整、逻辑连贯、内容驱动的中文综述写作大纲，并为大纲的每个部分规划建议的近似字数。

    ## 2. 背景与上下文
    - **核心主题 `{topic}`**: 这是整个综述的中心思想和贯穿始终的主线。所有大纲的设计都应围绕此主题展开。
    - **内容来源 `{literature_summary}`**: 这是你构建大纲主体部分的唯一信息来源。你需要深度分析这些摘要，识别其中的核心议题、研究发现和内在逻辑关联。

    ## 3. 关键步骤
    在你的创作过程中，请遵循以下内部步骤来构思和打磨作品：
    1.  **主题聚焦与内容吸收**: 首先，明确综述的核心主题 `{topic}`。然后，逐一深度阅读并理解所有提供的 `{literature_summary}`，提取关键信息，如研究背景、方法、主要发现、结论和局限性。
    2.  **核心议题聚类与提炼**: 将从摘要中提取的关键信息进行归纳和分类，形成3-5个逻辑上独立且相互关联的核心议题（Themes）。为每个议题构思一个精确、简洁的标题，这些标题将直接构成综述的**核心主体部分**。
    3.  **大纲结构化与排序**: 构建一个包含“引言”、“核心主体部分”和“结论与展望”的完整大纲框架。将上一步提炼出的核心议题标题，按照逻辑顺序（如：从基础到应用、从问题到解决方案、按时间发展等）填入“核心主体部分”。
    4.  **内容权重与字数规划**: 评估每个部分在综述中的重要性及内容支撑度。
        - 为“引言”和“结论与展望”分配标准的字数建议。
        - 根据每个核心主体议题在所提供摘要中的信息密度和重要性，为其分配合理的建议字数。信息丰富、重要的部分应获得更多的字数配额。
    5.  **最终审查与格式化**: 检查整个大纲的逻辑是否通顺，标题是否精炼，字数分配是否合理。确保最终输出严格符合下方“输出要求”中定义的格式。

    ## 4. 输出要求
    - **格式**: 使用Markdown的层级列表格式。
    - **风格**: 专业、学术、简洁。
    - **约束**:
        - 大纲必须包含标准的“引言”和“结论与展望”（或意义相近的标题，如“总结”）。
        - 核心主体部分的标题必须完全基于对 `{literature_summary}` 内容的分析和提炼。
        - 每个部分的标题后必须紧跟括号，注明建议字数，格式为 `(建议约 XXX 字)`。
        - **最终输出**: 你的最终回复应**严格且仅包含**最终生成的大纲本身。绝对禁止包含任何引导语、解释、分析过程、总结或其他任何非大纲内容。直接从“引言”开始输出。
review_generation:
  user_prompt_template: |
    # 任务：撰写一篇专业的中文医学综述文章

    **文章标题**: {title}

    # 角色：医学综述报告撰写专家

    # 任务
    请以提供的 **综述写作大纲** ('{outline_content}') 作为高级结构指导，并 **充分利用** 提供的 **多篇医学文献摘要** ('{literature_info}') 中的信息，撰写一篇逻辑严谨、结构清晰、内容完整的 **中文医学领域综述文章**。

    # 撰写要求
    1. **遵循大纲结构与处理标题:**
     * 文章的**主要章节结构**必须与给定的大纲标题顺序一致。
     * 在生成 Markdown 文章的章节标题时，请**使用**大纲中提供的标题文本，但**必须省略**括号及其内部的字数建议（即，忽略 `"(建议约 XXX 字)"` 这部分）。
     * 为这些主要的章节标题**添加顺序编号**。通常从"引言"开始编号为"1."，后续核心主体章节依次编号"2."、"3."... 直到最后的"结论与展望"部分。请使用 Markdown 的二级标题格式（`##`）来展示这些带编号的章节标题。例如：`## 1. 引言`，`## 2. [核心主体标题A]`，`## 3. [核心主体标题B]`， ... ，`## N. 结论与展望`。（注意：文章的总标题通常使用一级标题 `#` 且不带编号）。

    2. **参考字数规划 (内部使用):** 在撰写每个部分时，请**内部参考**大纲中提供的**建议字数**来把握内容的详略，但**不要**在最终输出的任何地方（包括标题或正文）提及这些字数。内容的逻辑完整性和表达清晰度是首要标准。

    3. **内容基于摘要:** 所有论点、分析和结论都应基于提供的文献摘要内容，进行整合、比较和分析。

    4. **标准综述格式:** 按照标准的医学综述文章格式进行撰写。

    5. **段落格式要求:**
     * **段落完整连续:** 每个自然段内部不需要额外分点列项，需写成连续、完整的段落文字。
     * **段首缩进:** 综述正文中的**每一个自然段**（不包括标题、列表项、代码块等）的开头，请**务必**添加**两个全角空格**（`　　`）以实现段首缩进。

    6. **文献引用要求:**
     * 在正文中引用相关文献摘要内容时，必须在相应位置通过**中括号数字**明确标注参考文献的序号，例如：`[1]`, `[2]`, `[3]`等。
     * 请**按照文献在摘要中出现的顺序**为引用分配序号（第1篇文献用`[1]`，第2篇用`[2]`，依此类推）。
     * **重要：不要在文章末尾添加参考文献列表**，参考文献列表将由系统自动处理和添加。

    7. **语言与逻辑:** 确保文章语言流畅、专业、准确，逻辑关系清晰，论证有力。

    8. **增强自然连贯性与逻辑流畅:**
     * **概念递进:** 通过相关概念的自然递进和展开来连接句子，而非依赖明显的连接词。
     * **语义关联:** 利用相关词汇、同义复述和概念关联来维持文本连贯性，使语义流动更为自然。
     * **上下文衔接:** 确保每个新句子明确地从前一句子的信息或概念中延伸发展。
     * **结构变化:** 混合使用不同句式结构（长短句搭配、主动被动转换）以创造节奏变化，避免机械单调感。
     * **论点链接:** 在阐述相关观点时，通过内容本身的关联性建立连接，而非依赖公式化的过渡标记。
     * **隐性过渡:** 使用隐含的逻辑关系和情境引导来替代显性的过渡词，让文本流动更自然。
     * **思路连贯展开:** 确保文章整体遵循清晰但不机械的思路发展脉络，让读者能够跟随自然的思维进程。
     * **避免套路化过渡:** 句子之间和段落之间要自然过渡，但减少使用过于明显的过渡词（如`"此外"`、`"然而"`等），转而采用更自然、多样化的语句连接方式。

    # **输出要求 (极其重要)**
    1. **最终结果必须保存为 Markdown (.md) 格式**。
    2. **你的输出必须严格地、仅仅包含完整的 Markdown 格式综述文章本身。**
    3. **绝对禁止**在 Markdown 文章内容之前或之后添加任何形式的引导语、解释、说明、确认信息、代码块标记说明（如 `"` ```markdown `"` 这种文字本身）或任何其他非文章正文的内容。
    4. 你的输出应该直接以文章的第一个字符（通常是总标题的 `#` 或第一个字）开始，并以文章的最后一个字符结束。
    5. **重要：文章结尾不要包含参考文献部分**，参考文献将由系统自动添加。

literature_filter:
  comprehensive: 请全面筛选文献，保留所有相关的研究，包括综述和原始研究
  default: 请根据以下标准筛选文献：高质量、相关性、最新性
  strict: 请严格筛选文献，只保留高质量且高度相关的研究
pubmed_search:
  comprehensive: 请进行全面的文献检索，包括{query}相关的所有研究，并按重要性排序
  default: 请搜索关于{query}的最新研究文献，重点关注过去5年的重要进展
  recent: 请搜索最近1-2年内关于{query}的最新研究进展