version: '3.8'

services:
  Intelligent-Literature-Review:
    image: ghcr.io/zhy0504/intelligent-literature-review:latest
    container_name: Intelligent-Literature-Review-TTY
    ports:
      - "8889:8889"  # WebSocket端口
      - "8890:8890"  # HTTP页面端口
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./cache:/app/cache
      - ./pubmed_cache:/app/pubmed_cache
      - ./output:/app/output
      - ./ai_config.yaml:/app/ai_config.yaml
      - ./prompts:/app/prompts
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - TZ=Asia/Shanghai
      - WEB_TTY=true  # 启用Web TTY模式
      # Web TTY认证配置
      - WEB_TTY_USERNAME=admin  # Web TTY用户名
      - WEB_TTY_PASSWORD=your_secure_password_here  # Web TTY密码，请修改！
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - literature-net

networks:
  literature-net:
    driver: bridge